# Generated by Django 3.2 on 2021-05-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.TextField()),
                ('pais', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
                ('rg', models.CharField(max_length=200)),
                ('data_de_nascimento', models.DateField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
