# Generated by Django 3.2 on 2021-05-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registermd', '0006_alter_publication_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='regiao',
            field=models.CharField(choices=[('BRASIL', 'BRASIL'), ('NORLA', 'NORLA'), ('CONOSUR', 'CONOSUR')], default='BRASIL', max_length=7),
        ),
    ]
