# Generated by Django 3.2 on 2021-05-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registermd', '0009_alter_publication_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='time',
            field=models.CharField(choices=[('A&KT', 'A&KT'), ('AS&D, Integration', 'AS&D, Integration'), ('AS & D, Integration', 'AS & D, Integration'), ('All MD Team', 'All MD Team'), ('Corn & Sorghum', 'Corn & Sorghum'), ('Crop Protection', 'Crop Protection'), ('MDR & FOE', 'MDR & FOE'), ('Soybean & Cotton', 'Soybean & Cotton')], default='A&KT', max_length=100),
        ),
    ]
